#!/usr/bin/env php
<?php

declare(ticks = 1);

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('FASTEST_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('FASTEST_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require FASTEST_COMPOSER_INSTALL;

$application = new \Liuggio\Fastest\Application();
$application->run();
