#!/usr/bin/env php
<?php

declare(ticks = 1);
$files = array(
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../vendor/autoload.php',
    __DIR__ . '/../../../vendor/autoload.php'
);

$found = false;

foreach ($files as $file) {
    $file = str_replace('/', DIRECTORY_SEPARATOR, $file);
    
    if (file_exists($file)) {
        require $file;
        $found = true;
        break;
    }
}

if (!$found) {
    die(
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
}


use Liuggio\Fastest\Application;
use Liuggio\Fastest\AppParametersFromEnv;


$application = new Application();
$application->run();

